In [1]:
import pandas as pd
df=pd.read_csv('C:/Users/DEEPADHARSHINI/OneDrive/Desktop/Cleaned_Crop_data.csv')

df.head()

,Area,Item,Year,Area harvested,Laying,Milk Animals,Producing Animals/Slaughtered,Production,Stocks,Yield,Yield/Carcass Weight
0,Afghanistan,"Almonds, in shell",2019,29203.0,NaN,NaN,NaN,38205.0,NaN,1308.3,NaN
1,Afghanistan,"Almonds, in shell",2020,22134.0,NaN,NaN,NaN,39307.0,NaN,1775.9,NaN
2,Afghanistan,"Almonds, in shell",2021,36862.0,NaN,NaN,NaN,64256.0,NaN,1743.2,NaN
3,Afghanistan,"Almonds, in shell",2022,36462.0,NaN,NaN,NaN,63515.0,NaN,1742.0,NaN
4,Afghanistan,"Almonds, in shell",2023,37000.0,NaN,NaN,NaN,67000.0,NaN,1810.8,NaN

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95925 entries, 0 to 95924
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Area                           95925 non-null  object
 1   Item                           95925 non-null  object
 2   Year                           95925 non-null  int64
 3   Area harvested                 50309 non-null  float64
 4   Laying                         1069 non-null   float64
 5   Milk Animals                   2146 non-null   float64
 6   Producing Animals/Slaughtered  18059 non-null  float64
 7   Production                     85303 non-null  float64
 8   Stocks                         8809 non-null   float64
 9   Yield                          50573 non-null  float64
 10  Yield/Carcass Weight           6307 non-null   float64
dtypes: float64(8), int64(1), object(2)
memory usage: 8.1+ MB

In [3]:
#label encoder

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

categorical_columns = ['Area', 'Item']

for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])

In [4]:
df = df.fillna(0)

df

,Area,Item,Year,Area harvested,Laying,Milk Animals,Producing Animals/Slaughtered,Production,Stocks,Yield,Yield/Carcass Weight
0,0,2,2019,29203.0,0.0,0.0,0.0,38205.000000,0.0,1308.3,0.0
1,0,2,2020,22134.0,0.0,0.0,0.0,39307.000000,0.0,1775.9,0.0
2,0,2,2021,36862.0,0.0,0.0,0.0,64256.000000,0.0,1743.2,0.0
3,0,2,2022,36462.0,0.0,0.0,0.0,63515.000000,0.0,1742.0,0.0
4,0,2,2023,37000.0,0.0,0.0,0.0,67000.000000,0.0,1810.8,0.0
...,...,...,...,...,...,...,...,...,...,...,...
95920,199,271,2019,0.0,0.0,0.0,0.0,5010.210000,0.0,0.0,0.0
95921,199,271,2020,0.0,0.0,0.0,0.0,4795.700000,0.0,0.0,0.0
95922,199,271,2021,0.0,0.0,0.0,0.0,4921.050000,0.0,0.0,0.0
95923,199,271,2022,0.0,0.0,0.0,0.0,4966.370000,0.0,0.0,0.0
95924,199,272,2019,0.0,0.0,0.0,0.0,898484.835892,0.0,0.0,0.0

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
df=df.dropna()

x=df.drop('Production',axis=1)
y=df['Production']


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

linear_model=LinearRegression()
linear_model.fit(x_train,y_train)

y_pred=linear_model.predict(x_test)

mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
R2=r2_score(y_test,y_pred)


print("Mean Square Error Value:",mse)
print("Mean Absolute Error Value:",mae)
print("R2 Square Value:",R2)

Mean Square Error Value: 98258492553209.27
Mean Absolute Error Value: 959310.9054312053
R2 Square Value: 0.34756520352570186

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
df=df.dropna()

x=df.drop('Production',axis=1)
y=df['Production']


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

rf_model=RandomForestRegressor()
rf_model.fit(x_train,y_train)

y_pred=rf_model.predict(x_test)

mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
R2=r2_score(y_test,y_pred)


print("Mean Square Error Value:",mse)
print("Mean Absolute Error Value:",mae)
print("R2 Square Value:",R2)

Mean Square Error Value: 30848077111793.547
Mean Absolute Error Value: 126802.45327375733
R2 Square Value: 0.795169268435931

In [7]:
from sklearn.ensemble import GradientBoostingRegressor



x=df.drop('Production',axis=1)
y=df['Production']


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

gb_model=GradientBoostingRegressor(n_estimators=100,learning_rate=0.1,max_depth=3,random_state=42)

gb_model.fit(x_train,y_train)

y_pred=gb_model.predict(x_test)

mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
R2=r2_score(y_test,y_pred)


print("Mean Square Error Value:",mse)
print("Mean Absolute Error Value:",mae)
print("R2 Square Value:",R2)

Mean Square Error Value: 27894595210981.836
Mean Absolute Error Value: 347650.63883320655
R2 Square Value: 0.8147803403420375